import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Footer } from 'src/components/Footer'
import { Main } from 'src/components/Main'
import { Header } from 'src/components/Header'
// import { useCouter } from 'src/hooks/useCouter'
// import { useInputArray } from 'src/hooks/useInputArray'
// import { useBgLightblue } from 'src/hooks/useBgLightblue'


const inter = Inter({ subsets: ['latin'] })

export default function About(props) {
  console.log(props);
  // useStateを使う
  // const { count, isShow, handleClick, handleDisplay } = useCouter();
  // const { text, array, handleChange, handleAdd } = useInputArray();
  const { count, isShow, handleClick, handleDisplay, text, array, handleChange, handleAdd } = props;

  // useBgLightblue();
  
  return (
    <>
      <Head>
        <title>About Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Header />

      <input type="text" value={text}
        onChange={handleChange}
      />

      {isShow ? <h1>{count}</h1> : null}
      <button onClick={handleClick}>ボタン</button>
        <button onClick={handleDisplay}>
          {isShow ? `非表示` : `表示`}
        </button>
        <button onClick={handleAdd}>追加</button>

        <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul>


      <Main page="about" />

      <Footer />
    </>
  )
}
